### PR TITLE
Use custom.cfg to set admin password

### LINKED ISSUE #12: Bug: Setting the password fails
When setting the `PASSWORD` environment variable on a new container I get the following error:

```
senaite_1  | Traceback (most recent call last):
senaite_1  |   File "bin/zope-passwd", line 309, in <module>
senaite_1  |     sys.exit(senaite.core.scripts.zope_passwd())
senaite_1  |   File "/home/senaite/senaitelims/src/senaite.core/src/senaite/core/scripts/__init__.py", line 79, in zope_passwd
senaite_1  |     return run_it("_zope_passwd")
senaite_1  |   File "/home/senaite/senaitelims/src/senaite.core/src/senaite/core/scripts/__init__.py", line 73, in run_it
senaite_1  |     module.run(app)
senaite_1  |   File "/home/senaite/senaitelims/src/senaite.core/src/senaite/core/scripts/_zope_passwd.py", line 24, in run
senaite_1  |     users = app.acl_users.users
senaite_1  | AttributeError: 'RequestContainer' object has no attribute 'users'
```

tested on latest 2.x image (`8c142a35419a`)

### PR DESCRIPTION
**Pull request by winniehell**
fixes https://github.com/senaite/senaite.docker/issues/12

### CODE REVIEW

File: latest/docker-entrypoint.sh [hunk 1]
```diff
@@ -25,9 +25,9 @@ if [[ "$1" == "zeo"* ]]; then
   exec gosu senaite bin/$1 fg
 fi
 
-# Change the password
 if [[ -n "${PASSWORD}" ]]; then
-    gosu senaite bin/zope-passwd -p "${PASSWORD}"
```
Comment (winniehell) [inline latest/docker-entrypoint.sh:30]: of course it would be better to get `zope-passwd` working again but unfortunately I have no idea how to do that :disappointed:

**Comment by winniehell** [comment]
I'm going to update this with the insight gained from https://github.com/senaite/senaite.docker/issues/12#issuecomment-1207277360

File: latest/docker-initialize.py [hunk 2]
```diff
@@ -227,23 +232,27 @@ def setup(self, **kwargs):
 BUILDOUT_TEMPLATE = """
 [buildout]
 extends = buildout.cfg
+user=admin:{password}
```
Comment (winniehell) [inline latest/docker-initialize.py:235]: this overrides https://github.com/senaite/senaite.docker/blob/353c42805c683b2c7c3ab7dcf046689e15f20d39/latest/buildout.cfg#L12

File: latest/docker-initialize.py [hunk 3]
```diff
@@ -150,28 +150,33 @@ def buildout(self):
...
             zcml="\n\t".join(zcml),
             develop="\n\t".join(develop),
-            profiles="\n\t".join(profiles),
             versions="\n".join(versions),
             sources="\n".join(sources),
-            site=site or "senaite",
-            enabled=enabled,
         )
 
+        if site:
```
Comment (winniehell) [inline latest/docker-initialize.py:174]: from my perspective it is surprising if a site config is included even though no site (URL) was specified.

also what benefits do we have from a site config with default URL which is not `enabled`?

**Comment by winniehell** [comment]
@ramonski I have tested this without environment variables (default password, no site config/installation), with only site variable (default password), and custom password (no site config/installation). in my opinion this behaves as expected now.

**Comment by winniehell** [comment]
@ramonski do you have time to take another look at this?

**Review by ramonski — APPROVED** [review]
Thanks!
